[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
